import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  buildHostnameIndex,
  getProjectFromHostname,
  loadProjectList,
} from "../src/utils/ddev.js";

describe("buildHostnameIndex", () => {
  it("builds hostname index from projects", () => {
    const projects = new Map([
      ["my-project", "/home/ddev/www/my-project"],
      ["another-app", "/home/ddev/www/another-app"],
    ]);

    const index = buildHostnameIndex(projects, "preview.example.com");

    expect(index.get("my-project.preview.example.com")).toBe("my-project");
    expect(index.get("another-app.preview.example.com")).toBe("another-app");
    expect(index.size).toBe(2);
  });

  it("handles empty projects", () => {
    const index = buildHostnameIndex(new Map(), "example.com");
    expect(index.size).toBe(0);
  });
});

describe("getProjectFromHostname", () => {
  const projects = new Map([
    ["my-project", "/home/ddev/www/my-project"],
    ["preview-42--starter", "/home/ddev/www/preview-42--starter"],
  ]);
  const index = buildHostnameIndex(projects, "preview.example.com");

  it("returns project name for valid hostname", () => {
    expect(getProjectFromHostname("my-project.preview.example.com", index)).toBe(
      "my-project",
    );
  });

  it("handles preview environments", () => {
    expect(
      getProjectFromHostname("preview-42--starter.preview.example.com", index),
    ).toBe("preview-42--starter");
  });

  it("returns undefined for unknown hostname", () => {
    expect(
      getProjectFromHostname("unknown.preview.example.com", index),
    ).toBeUndefined();
  });

  it("returns undefined for wrong TLD", () => {
    expect(getProjectFromHostname("my-project.other.com", index)).toBeUndefined();
  });
});

describe("loadProjectList", () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "trafic-project-list-"));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  /** Write a project_list.yaml and load it. */
  function load(content: string): Map<string, string> {
    const path = join(dir, "project_list.yaml");
    writeFileSync(path, content);
    return loadProjectList(path);
  }

  it("reads the approot nested under the project name", () => {
    const projects = load(
      "scalian:\n    approot: /home/ddev/www/scalian\n",
    );

    expect(projects.size).toBe(1);
    expect(projects.get("scalian")).toBe("/home/ddev/www/scalian");
  });

  it("does not invent a project called approot", () => {
    const projects = load(
      "scalian:\n    approot: /home/ddev/www/scalian\n",
    );

    // A flat key/value pass produced this phantom, and the TLS ask endpoint
    // would then vouch for approot.<tld> and have a certificate issued
    expect(projects.has("approot")).toBe(false);
  });

  it("reads several projects", () => {
    const projects = load(
      [
        "scalian:",
        "    approot: /home/ddev/www/scalian",
        "preview-42--scalian:",
        "    approot: /home/ddev/www/preview-42--scalian",
        "",
      ].join("\n"),
    );

    expect(projects.size).toBe(2);
    expect(projects.get("preview-42--scalian")).toBe(
      "/home/ddev/www/preview-42--scalian",
    );
  });

  it("keeps a project whose approot is absent", () => {
    const projects = load("scalian:\n");

    // It still owns its hostname, so auth must still resolve it
    expect(projects.get("scalian")).toBe("");
  });

  it("ignores comments and blank lines", () => {
    const projects = load(
      [
        "# generated by ddev",
        "",
        "scalian:",
        "    approot: /home/ddev/www/scalian",
        "",
      ].join("\n"),
    );

    expect(projects.size).toBe(1);
    expect(projects.get("scalian")).toBe("/home/ddev/www/scalian");
  });

  it("strips quotes around a path", () => {
    const projects = load(
      "scalian:\n    approot: \"/home/ddev/www/my project\"\n",
    );

    expect(projects.get("scalian")).toBe("/home/ddev/www/my project");
  });

  it("ignores other nested keys", () => {
    const projects = load(
      [
        "scalian:",
        "    approot: /home/ddev/www/scalian",
        "    status: running",
        "",
      ].join("\n"),
    );

    expect(projects.size).toBe(1);
    expect(projects.get("scalian")).toBe("/home/ddev/www/scalian");
  });

  it("returns nothing for a missing file", () => {
    expect(loadProjectList(join(dir, "absent.yaml")).size).toBe(0);
  });

  it("feeds the hostname index only real projects", () => {
    const projects = load(
      "scalian:\n    approot: /home/ddev/www/scalian\n",
    );
    const index = buildHostnameIndex(projects, "preprod.ikko.fr");

    expect(index.get("scalian.preprod.ikko.fr")).toBe("scalian");
    expect(index.has("approot.preprod.ikko.fr")).toBe(false);
    expect(index.size).toBe(1);
  });
});
