import { nodeIo, type SetupIo } from "./io.js";
import { step, success, info } from "./steps.js";

/** Node.js major version required by the agent */
const NODE_MAJOR = 24;

/** NodeSource keyring path */
const NODESOURCE_KEYRING = "/etc/apt/keyrings/nodesource.gpg";

/**
 * Add the NodeSource apt repository and GPG key.
 * Idempotent: safe to call even if the repository is already configured.
 *
 * nodejs.org points at NodeSource for apt installs. The Ubuntu 24.04
 * `nodejs` package is 18.x, far below what the agent needs.
 */
export function addNodeSourceAptRepo(io: SetupIo = nodeIo): void {
  io.exec("install -m 0755 -d /etc/apt/keyrings", { silent: true });
  // Download and dearmor as separate commands: piping curl into gpg into tee
  // would report only tee's exit code and hide a failed key download, which
  // then surfaces as a confusing GPG error on the next apt-get update
  io.exec(
    "curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key -o /tmp/trafic-nodesource.key",
    { silent: true },
  );
  io.exec(
    "gpg --batch --yes --dearmor -o /tmp/trafic-nodesource.gpg /tmp/trafic-nodesource.key",
    { silent: true },
  );
  io.exec(`install -m 0644 /tmp/trafic-nodesource.gpg ${NODESOURCE_KEYRING}`, {
    silent: true,
  });
  io.exec("rm -f /tmp/trafic-nodesource.key /tmp/trafic-nodesource.gpg", {
    silent: true,
  });
  io.exec(
    `echo "deb [signed-by=${NODESOURCE_KEYRING}] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list > /dev/null`,
    { silent: true },
  );
}

/**
 * Install Node.js from the NodeSource apt repository.
 *
 * apt keeps node and npm in /usr/bin — on root's PATH, so `which
 * trafic-agent` resolves for the systemd unit — and unattended-upgrades
 * patches them, which a version manager install never gets.
 */
export function installNode(io: SetupIo = nodeIo): void {
  step("Install Node.js");

  // Check if Node is already installed
  if (io.commandExists("node")) {
    const version = io.exec("node --version", { silent: true });
    info(`Node.js already installed: ${version?.trim()}`);
    return;
  }

  info("Adding NodeSource apt repository...");
  addNodeSourceAptRepo(io);

  info("Installing Node.js...");
  io.exec("apt-get update -qq", { silent: true });
  io.exec(
    "DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a apt-get install -y nodejs",
    { silent: true },
  );

  success(`Node.js ${NODE_MAJOR} installed from apt`);
}

/**
 * Install the Trafic agent
 */
export function installAgent(io: SetupIo = nodeIo): void {
  step("Install Trafic agent");

  // Install the agent globally
  io.exec("npm install -g @studiometa/trafic-agent");

  success("Trafic agent installed");
}

/**
 * Create the agent configuration
 */
export function createAgentConfig(
  tld: string,
  _email?: string,
  io: SetupIo = nodeIo,
): void {
  step("Create agent configuration");

  // Create directories
  io.exec("mkdir -p /etc/trafic");
  io.exec("mkdir -p /var/lib/trafic");
  io.exec("chown ddev:ddev /var/lib/trafic");

  const configPath = "/etc/trafic/config.toml";

  if (io.fileExists(configPath)) {
    info("Configuration already exists at /etc/trafic/config.toml — skipping");
    info("Edit this file to configure authentication");
    return;
  }

  const config = `# Trafic agent configuration
# Generated by trafic setup

# Required: TLD for DDEV projects
tld = "${tld}"

# Agent HTTP server port
port = 9876

# Database and paths
db_path = "/var/lib/trafic/db.sqlite"
project_list_path = "/home/ddev/.ddev/project_list.yaml"
projects_dir = "/home/ddev/www"

# Scale-to-zero settings
idle_timeout = "4h"
idle_check_interval = "5m"

# Authentication
[auth]
default_policy = "basic"
allowed_ips = []
tokens = []
basic_auth = []
rules = []
`;

  io.writeFile(configPath, config);
  io.exec("chmod 640 /etc/trafic/config.toml");
  io.exec("chown root:ddev /etc/trafic/config.toml");

  success("Configuration created at /etc/trafic/config.toml");
  info("Edit this file to configure authentication");
}

/**
 * Create systemd service for the agent
 */
export function createSystemdService(io: SetupIo = nodeIo): void {
  step("Create systemd service");

  // Find the trafic-agent binary path
  const agentPath = io.exec("which trafic-agent", { silent: true })?.trim() || "/usr/bin/trafic-agent";

  const serviceContent = `[Unit]
Description=Trafic Agent - DDEV preview environment manager
After=network.target docker.service
Requires=docker.service

[Service]
Type=simple
User=ddev
Group=ddev
ExecStart=${agentPath} start --config /etc/trafic/config.toml
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=trafic-agent

# Environment
Environment=NODE_ENV=production
# Skip ddev-hostname /etc/hosts management — on a server, hostnames resolve
# to the public IP (not localhost), which would trigger ddev-hostname on every
# ddev start. DDEV_NONINTERACTIVE=true skips that entirely.
Environment=DDEV_NONINTERACTIVE=true

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=/var/lib/trafic /home/ddev/.ddev
PrivateTmp=true

[Install]
WantedBy=multi-user.target
`;

  io.writeFile("/etc/systemd/system/trafic-agent.service", serviceContent);
  io.exec("chmod 644 /etc/systemd/system/trafic-agent.service");

  // Reload systemd and enable service
  io.exec("systemctl daemon-reload");
  io.exec("systemctl enable trafic-agent");
  io.exec("systemctl start trafic-agent");

  success("Trafic agent service started");
  info("View logs: journalctl -u trafic-agent -f");
}
