import { nodeIo, type SetupIo } from "./io.js";
import { step, success, info } from "./steps.js";

/** Where the rule script lives, so systemd and a human can both run it. */
export const DOCKER_FIREWALL_SCRIPT = "/usr/local/sbin/trafic-docker-firewall";

/** The unit that reapplies the rules after Docker starts. */
export const DOCKER_FIREWALL_UNIT =
  "/etc/systemd/system/trafic-docker-firewall.service";

/**
 * Docker's own bridge ranges, exempted so containers and the host gateway can
 * still reach a published port. Containers normally talk to each other by
 * container address rather than through the published port, so this is a
 * safety valve rather than a requirement.
 */
const DOCKER_IPV4_NETS = "172.16.0.0/12";
const DOCKER_IPV6_NETS = "fd00::/8";

/**
 * Build the script that restricts the ports ddev-router publishes for DDEV's
 * tools (Mailpit, xhgui) to Docker's own networks.
 *
 * UFW cannot express this. Docker puts its DNAT in `nat/PREROUTING` and its
 * filtering in the `DOCKER` chain of `FORWARD`, both evaluated before UFW's
 * chains, so `ufw default deny incoming` never sees these packets.
 * `DOCKER-USER` is the hook Docker provides for exactly this case: it is
 * jumped to first in `FORWARD` and Docker never flushes it.
 *
 * A network-edge firewall is not a substitute. Measured on an OVH server with
 * its Edge Firewall enabled and a correct deny-all rule: a published tool port
 * still accepted a connection from another host inside OVH in 114ms, while a
 * port with nothing listening was dropped and timed out at 12s. Anyone who can
 * rent a VM from the same provider is inside that blind spot. These rules
 * apply to every packet regardless of where it came from.
 *
 * The match is on the *original* destination port. By the time a packet
 * reaches `FORWARD`, DNAT has rewritten the destination to the container, so
 * `--dport` would be matching the container's port — the same number today,
 * but not if a published port and a container port ever differ.
 */
export function buildDockerFirewallScript(toolPorts: string[]): string {
  return `#!/bin/sh
# Trafic: restrict the ports ddev-router publishes for DDEV's tools.
#
# Generated by trafic-agent setup. Reapplied at boot by
# trafic-docker-firewall.service, because Docker recreates DOCKER-USER empty
# and nothing else restores what we put there.
#
# Why not UFW: Docker's DNAT sits in nat/PREROUTING and its filtering in the
# DOCKER chain of FORWARD, both evaluated before UFW's chains, so
# "ufw default deny incoming" never sees these packets. DOCKER-USER is the
# hook Docker provides — jumped to first in FORWARD, never flushed by Docker.
#
# Why not only a provider firewall: measured on OVH with its Edge Firewall
# enabled and denying these ports, a connection from another host inside OVH
# still succeeded. A network-edge filter can have blind spots for traffic that
# never crosses the edge. These rules do not.
#
# The match is on the ORIGINAL destination port: after DNAT the destination is
# the container, so --dport would match the wrong side of the mapping.
set -eu

PORTS="${toolPorts.join(" ")}"

apply() {
  cmd="$1"
  nets="$2"

  command -v "$cmd" >/dev/null 2>&1 || return 0

  for port in $PORTS; do
    # Drop any previous copy first, so running this twice does not stack rules
    while "$cmd" -C DOCKER-USER -p tcp -m conntrack --ctorigdstport "$port" \\
      --ctdir ORIGINAL -j DROP 2>/dev/null; do
      "$cmd" -D DOCKER-USER -p tcp -m conntrack --ctorigdstport "$port" \\
        --ctdir ORIGINAL -j DROP
    done
    while "$cmd" -C DOCKER-USER -p tcp -s "$nets" -m conntrack \\
      --ctorigdstport "$port" --ctdir ORIGINAL -j RETURN 2>/dev/null; do
      "$cmd" -D DOCKER-USER -p tcp -s "$nets" -m conntrack \\
        --ctorigdstport "$port" --ctdir ORIGINAL -j RETURN
    done

    # Insert the DROP first, then the RETURN above it, so Docker's own
    # networks keep working and everything else is dropped
    "$cmd" -I DOCKER-USER -p tcp -m conntrack --ctorigdstport "$port" \\
      --ctdir ORIGINAL -j DROP
    "$cmd" -I DOCKER-USER -p tcp -s "$nets" -m conntrack \\
      --ctorigdstport "$port" --ctdir ORIGINAL -j RETURN
  done
}

apply iptables ${DOCKER_IPV4_NETS}
apply ip6tables ${DOCKER_IPV6_NETS}
`;
}

/** The systemd unit that reapplies the rules after Docker starts. */
export function buildDockerFirewallUnit(): string {
  return `[Unit]
Description=Trafic - restrict Docker-published DDEV tool ports
# Docker recreates DOCKER-USER empty on start, so the rules have to go back
# afterwards. PartOf means a docker restart reapplies them too.
After=docker.service
Requires=docker.service
PartOf=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=${DOCKER_FIREWALL_SCRIPT}

[Install]
WantedBy=multi-user.target
`;
}

/**
 * Install and enable the DOCKER-USER rules.
 */
export function configureDockerFirewall(
  toolPorts: string[],
  io: SetupIo = nodeIo,
): void {
  step("Restrict Docker-published tool ports");

  io.writeFile(DOCKER_FIREWALL_SCRIPT, buildDockerFirewallScript(toolPorts));
  io.exec(`chmod 0755 ${DOCKER_FIREWALL_SCRIPT}`, { silent: true });

  io.writeFile(DOCKER_FIREWALL_UNIT, buildDockerFirewallUnit());
  io.exec("systemctl daemon-reload", { silent: true });
  io.exec("systemctl enable --now trafic-docker-firewall.service", {
    silent: true,
  });

  success(`Tool ports restricted to Docker networks: ${toolPorts.join(", ")}`);
  info("These live in DOCKER-USER, not UFW — `ufw status` will not show them");
}
