import { nodeIo, type SetupIo } from "./io.js";
import { step, success, info, warn } from "./steps.js";

/**
 * Resolve the users listed in AllowUsers.
 *
 * The user who invoked sudo is always included. Without them, the
 * AllowUsers directive locks them out on their next connection, and
 * reloading sshd keeps the current session alive so nothing looks wrong
 * until it is too late. root needs no entry — it is always listed.
 */
export function resolveAllowedUsers(
  allowedUsers: string[],
  sudoUser: string | undefined,
): string[] {
  const users = allowedUsers.map((user) => user.trim()).filter(Boolean);

  if (sudoUser && sudoUser !== "root" && !users.includes(sudoUser)) {
    users.push(sudoUser);
  }

  return users;
}

/**
 * Configure SSH hardening
 */
export function hardenSsh(
  allowedUsers: string[] = ["ddev"],
  io: SetupIo = nodeIo,
): void {
  step("Harden SSH configuration");

  const users = resolveAllowedUsers(allowedUsers, io.env.SUDO_USER);

  const sshConfig = `# Trafic SSH hardening
# Generated by trafic setup

# Allow root login via SSH key only (no password) — required for server management
PermitRootLogin prohibit-password

# Disable password authentication (keys only)
PasswordAuthentication no
PubkeyAuthentication yes

# Limit authentication attempts
MaxAuthTries 3

# Idle timeout (5 minutes)
ClientAliveInterval 300
ClientAliveCountMax 2

# Allowed users (root kept for emergency access)
AllowUsers root ${users.join(" ")}

# Disable X11 forwarding
X11Forwarding no

# Disable TCP forwarding
AllowTcpForwarding no

# Use strong algorithms only
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
`;

  io.writeFile("/etc/ssh/sshd_config.d/trafic.conf", sshConfig);
  io.exec("chmod 644 /etc/ssh/sshd_config.d/trafic.conf");

  // Test config before restarting
  const testResult = io.exec("sshd -t 2>&1 || echo 'error'", { silent: true });
  if (testResult?.includes("error")) {
    warn("SSH config test failed, reverting...");
    io.exec("rm /etc/ssh/sshd_config.d/trafic.conf");
    return;
  }

  io.exec("systemctl reload ssh || systemctl reload sshd");
  success("SSH hardened: password auth disabled, root key-only login retained");
  info(`Allowed users: root, ${users.join(", ")}`);
}

/**
 * Configure UFW firewall
 */
export function configureFirewall(io: SetupIo = nodeIo): void {
  step("Configure firewall (UFW)");

  // Install UFW if not present
  if (!io.commandExists("ufw")) {
    io.exec("DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a apt-get install -y ufw", { silent: true });
  }

  // Reset and configure
  io.exec("ufw --force reset", { silent: true });
  io.exec("ufw default deny incoming");
  io.exec("ufw default allow outgoing");
  io.exec("ufw allow 22/tcp comment 'SSH'");
  io.exec("ufw allow 80/tcp comment 'HTTP'");
  io.exec("ufw allow 443/tcp comment 'HTTPS'");
  // Allow trafic-agent port from Docker bridge subnets so ddev-router can
  // reach the forward-auth endpoint. Docker typically uses 172.16.0.0/12.
  io.exec("ufw allow from 172.16.0.0/12 to any port 9876 comment 'trafic-agent from Docker'");

  // Enable firewall
  io.exec("ufw --force enable");

  success("Firewall enabled: SSH (22), HTTP (80), HTTPS (443), trafic-agent (9876 from Docker) allowed");
}

/**
 * Configure automatic security updates
 */
export function configureUnattendedUpgrades(io: SetupIo = nodeIo): void {
  step("Configure automatic security updates");

  // Install unattended-upgrades
  io.exec(
    "DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a apt-get install -y unattended-upgrades apt-listchanges",
    { silent: true },
  );

  // Configure for security updates only
  const upgradesConfig = `// Trafic: Automatic security updates
Unattended-Upgrade::Allowed-Origins {
    "\${distro_id}:\${distro_codename}";
    "\${distro_id}:\${distro_codename}-security";
    "\${distro_id}ESMApps:\${distro_codename}-apps-security";
    "\${distro_id}ESM:\${distro_codename}-infra-security";
};

// Do not automatically reboot
Unattended-Upgrade::Automatic-Reboot "false";

// Remove unused dependencies
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Email notifications (optional)
// Unattended-Upgrade::Mail "root";
`;

  io.writeFile(
    "/etc/apt/apt.conf.d/50unattended-upgrades",
    upgradesConfig,
  );

  // Enable automatic updates
  const autoConfig = `APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
`;

  io.writeFile("/etc/apt/apt.conf.d/20auto-upgrades", autoConfig);

  // Enable the service
  io.exec("systemctl enable unattended-upgrades");
  io.exec("systemctl start unattended-upgrades");

  success("Automatic security updates enabled");
}

/**
 * Configure Fail2ban
 */
export function configureFail2ban(io: SetupIo = nodeIo): void {
  step("Configure Fail2ban");

  // Install fail2ban
  if (!io.commandExists("fail2ban-client")) {
    io.exec("DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a apt-get install -y fail2ban", { silent: true });
  }

  // Configure jail
  const jailConfig = `# Trafic: Fail2ban configuration
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 5
backend = auto

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 7200
`;

  io.writeFile("/etc/fail2ban/jail.local", jailConfig);
  io.exec("chmod 644 /etc/fail2ban/jail.local");

  // Restart fail2ban
  io.exec("systemctl enable fail2ban");
  io.exec("systemctl restart fail2ban");

  success("Fail2ban enabled: SSH brute force protection active");
}

/**
 * Configure system limits
 */
export function configureSystemLimits(io: SetupIo = nodeIo): void {
  step("Configure system limits");

  const limitsConfig = `# Trafic: System limits for ddev user
ddev soft nofile 65536
ddev hard nofile 65536
ddev soft nproc 4096
ddev hard nproc 4096
`;

  io.writeFile("/etc/security/limits.d/trafic.conf", limitsConfig);
  io.exec("chmod 644 /etc/security/limits.d/trafic.conf");

  success("System limits configured for ddev user");
}

/**
 * Set proper file permissions
 */
export function configureFilePermissions(io: SetupIo = nodeIo): void {
  step("Configure file permissions");

  // Create directories
  io.exec("mkdir -p /etc/trafic");
  io.exec("mkdir -p /var/lib/trafic");
  io.exec("mkdir -p /var/backups/trafic");

  // Set permissions
  io.exec("chmod 755 /etc/trafic");
  io.exec("chmod 700 /var/lib/trafic");
  io.exec("chmod 700 /var/backups/trafic");
  io.exec("chown root:ddev /etc/trafic");
  io.exec("chown ddev:ddev /var/lib/trafic");
  io.exec("chown ddev:ddev /var/backups/trafic");

  // Config file (if exists)
  if (io.fileExists("/etc/trafic/config.toml")) {
    io.exec("chmod 640 /etc/trafic/config.toml");
    io.exec("chown root:ddev /etc/trafic/config.toml");
  }

  success("File permissions configured");
}

/**
 * Run all hardening steps
 */
export function hardenServer(
  sshUsers: string[] = ["ddev"],
  io: SetupIo = nodeIo,
): void {
  hardenSsh(sshUsers, io);
  configureFirewall(io);
  configureUnattendedUpgrades(io);
  configureFail2ban(io);
  configureSystemLimits(io);
  configureFilePermissions(io);
}
