import { step, success, info, exec, warn, commandExists } from "./steps.js";
import { writeFileSync, existsSync } from "node:fs";

/**
 * Configure SSH hardening
 */
export function hardenSsh(allowedUsers: string[] = ["ddev"]): void {
  step("Harden SSH configuration");

  const sshConfig = `# Trafic SSH hardening
# Generated by trafic setup

# Disable root login
PermitRootLogin no

# Disable password authentication (keys only)
PasswordAuthentication no
PubkeyAuthentication yes

# Limit authentication attempts
MaxAuthTries 3

# Idle timeout (5 minutes)
ClientAliveInterval 300
ClientAliveCountMax 2

# Allowed users
AllowUsers ${allowedUsers.join(" ")}

# Disable X11 forwarding
X11Forwarding no

# Disable TCP forwarding
AllowTcpForwarding no

# Use strong algorithms only
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
`;

  writeFileSync("/etc/ssh/sshd_config.d/trafic.conf", sshConfig);
  exec("chmod 644 /etc/ssh/sshd_config.d/trafic.conf");

  // Test config before restarting
  const testResult = exec("sshd -t 2>&1 || echo 'error'", { silent: true });
  if (testResult?.includes("error")) {
    warn("SSH config test failed, reverting...");
    exec("rm /etc/ssh/sshd_config.d/trafic.conf");
    return;
  }

  exec("systemctl reload sshd || systemctl reload ssh");
  success("SSH hardened: root login disabled, password auth disabled");
  info(`Allowed users: ${allowedUsers.join(", ")}`);
}

/**
 * Configure UFW firewall
 */
export function configureFirewall(): void {
  step("Configure firewall (UFW)");

  // Install UFW if not present
  if (!commandExists("ufw")) {
    exec("apt-get update && apt-get install -y ufw", { silent: true });
  }

  // Reset and configure
  exec("ufw --force reset", { silent: true });
  exec("ufw default deny incoming");
  exec("ufw default allow outgoing");
  exec("ufw allow 22/tcp comment 'SSH'");
  exec("ufw allow 80/tcp comment 'HTTP'");
  exec("ufw allow 443/tcp comment 'HTTPS'");

  // Enable firewall
  exec("ufw --force enable");

  success("Firewall enabled: SSH (22), HTTP (80), HTTPS (443) allowed");
}

/**
 * Configure automatic security updates
 */
export function configureUnattendedUpgrades(): void {
  step("Configure automatic security updates");

  // Install unattended-upgrades
  exec(
    "DEBIAN_FRONTEND=noninteractive apt-get install -y unattended-upgrades apt-listchanges",
    { silent: true },
  );

  // Configure for security updates only
  const upgradesConfig = `// Trafic: Automatic security updates
Unattended-Upgrade::Allowed-Origins {
    "\${distro_id}:\${distro_codename}";
    "\${distro_id}:\${distro_codename}-security";
    "\${distro_id}ESMApps:\${distro_codename}-apps-security";
    "\${distro_id}ESM:\${distro_codename}-infra-security";
};

// Do not automatically reboot
Unattended-Upgrade::Automatic-Reboot "false";

// Remove unused dependencies
Unattended-Upgrade::Remove-Unused-Dependencies "true";

// Email notifications (optional)
// Unattended-Upgrade::Mail "root";
`;

  writeFileSync(
    "/etc/apt/apt.conf.d/50unattended-upgrades",
    upgradesConfig,
  );

  // Enable automatic updates
  const autoConfig = `APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
`;

  writeFileSync("/etc/apt/apt.conf.d/20auto-upgrades", autoConfig);

  // Enable the service
  exec("systemctl enable unattended-upgrades");
  exec("systemctl start unattended-upgrades");

  success("Automatic security updates enabled");
}

/**
 * Configure Fail2ban
 */
export function configureFail2ban(): void {
  step("Configure Fail2ban");

  // Install fail2ban
  if (!commandExists("fail2ban-client")) {
    exec("apt-get update && apt-get install -y fail2ban", { silent: true });
  }

  // Configure jail
  const jailConfig = `# Trafic: Fail2ban configuration
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 5
backend = auto

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 7200
`;

  writeFileSync("/etc/fail2ban/jail.local", jailConfig);
  exec("chmod 644 /etc/fail2ban/jail.local");

  // Restart fail2ban
  exec("systemctl enable fail2ban");
  exec("systemctl restart fail2ban");

  success("Fail2ban enabled: SSH brute force protection active");
}

/**
 * Configure system limits
 */
export function configureSystemLimits(): void {
  step("Configure system limits");

  const limitsConfig = `# Trafic: System limits for ddev user
ddev soft nofile 65536
ddev hard nofile 65536
ddev soft nproc 4096
ddev hard nproc 4096
`;

  writeFileSync("/etc/security/limits.d/trafic.conf", limitsConfig);
  exec("chmod 644 /etc/security/limits.d/trafic.conf");

  success("System limits configured for ddev user");
}

/**
 * Set proper file permissions
 */
export function configureFilePermissions(): void {
  step("Configure file permissions");

  // Create directories
  exec("mkdir -p /etc/trafic");
  exec("mkdir -p /var/lib/trafic");
  exec("mkdir -p /var/backups/trafic");

  // Set permissions
  exec("chmod 755 /etc/trafic");
  exec("chmod 700 /var/lib/trafic");
  exec("chmod 700 /var/backups/trafic");
  exec("chown root:ddev /etc/trafic");
  exec("chown ddev:ddev /var/lib/trafic");
  exec("chown ddev:ddev /var/backups/trafic");

  // Config file (if exists)
  if (existsSync("/etc/trafic/config.toml")) {
    exec("chmod 640 /etc/trafic/config.toml");
    exec("chown root:ddev /etc/trafic/config.toml");
  }

  success("File permissions configured");
}

/**
 * Run all hardening steps
 */
export function hardenServer(sshUsers: string[] = ["ddev"]): void {
  hardenSsh(sshUsers);
  configureFirewall();
  configureUnattendedUpgrades();
  configureFail2ban();
  configureSystemLimits();
  configureFilePermissions();
}
